### PR TITLE
Add temperature & humidity specifiers to HTTP Action content

### PR DESCRIPTION
**Pull request by WizBangCrash**
Hi Jose,
Dave Dix here :-)
I wondered if you were prepared to merge in this feature I have added to HAA?
It enables a user to specify the temperature or humidity sensor values in an HTTP Action content.
I'm now using it to have my temperature sensors push their temperature values to an InfluxDB every 5 mins. It works great :-)
If the HTTP content string contains the characters `{T}` or `{H}` then the http action replaces those specifiers with the actual temperature sensor or humidity sensor values.

If you are happy to add it I will update the docs to give an example of using it.

Here's an example of how I am using it:
```json
{
  "c":{
    "n":"office-sensor",
    "u":0,
    "o":4
  },
  "a":[{
    "t":22,
    "n":6,
    "j":300,
    "y0": [{
      "v": 0,
      "r": 1,
      "0": { "h": [{ "h": "192.168.111.11", "p": 8086, "m": 2, "u": "write?db=testdb", "c": "sensor,location=office temperature={T}" }] }
    }]
  },{
    "t":1,
    "0":{"r":[{"g":13,"v":0}]},
    "1":{"r":[{"g":13,"v":1}]}
  },{
    "t": 1,
    "i":0.5,
    "1":{"s":[{"a":1}]}
  }]
}```

### CODE REVIEW

**Comment by RavenSystem** [comment]
Hi Dave,

I want to include those values into HTTP requests, but not only temperature. It is necessary to create a system where you can define which HomeKit characteristic you want to read: temperature, light status, target cooler temperature, % of a window cover, ... That is the spirit of HAA.

**Comment by WizBangCrash** [comment]
Hi Jose,
Understood. I’m working on a more generic version. Should have something to share later in the week :-)

Dave.

**Comment by RavenSystem** [comment]
Don't worry. I will release that feature with the next version.

**Comment by RavenSystem** [comment]
Supported with v2.5.0. https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_2.5.0

**Pull request closed without merging**
