### PR TITLE
my92xx LED Driver support for Light bulb accessory

### PR DESCRIPTION
**Pull request by lougovsk**
The suggested changes are bringing my92xx LED drive support to the Light bulb accessory. The my92xx driver itself is my port of the C++ library (https://github.com/xoseperez/my92xx) with some required modifications and simplifications. I've tried to integrate the driver in the similar manner as the pwm. That's why there is only limited amount of code changes in the main.c
A better solution would be of course  to use a generalized interface for both pwm and drivers but I don't see a simple and intuitive solution for this right now. Therefore, for now my solution uses couple of if/else statements. 
I have tested my changes with a Lohas lamp (with my9291 on board), however couldn't test if the pwm is still functional due to the absence of the corresponding HW.

### CODE REVIEW

**Comment by lougovsk** [comment]
@RavenSystem  I have reworked the original concept, now it seems to be done pretty generic. As an addition I've implemented a simple ws2812 wrapper based on the open rtos module. Please can you take a look at the suggested changes and let me know if there is something else I can do to finish the pull request.
PS: I could only test it with my9291 driver. Unfortunately, I don't have neither bulb which uses PWM nor one which uses ws2812(b)

**Comment by lougovsk** [comment]
@glumb , @pandarek not interested?

**Comment by RavenSystem** [comment]
It is interesting, but I need enough free time to review it.

**Comment by RavenSystem** [comment]
It is interesting, but I need enough free time to review it.

**Comment by lougovsk** [comment]
Sure. Take your time. Just let me know if you need more info or some rework is required.

**Comment by lougovsk** [comment]
Keeping the pull-request alive :)

**Comment by wayn3** [comment]
Hey @lougovsk you should join the [RGBWCWWW Discord Chat](https://discord.gg/v8hyxj2), you might find it interesting and be able to assist others in designing or implementing an even better light for HAA

**Comment by lougovsk** [comment]
@wayn3 thanks a lot for the hint. I will keep an eye on the channel.

**Comment by RavenSystem** [comment]
@lougovsk I will review this after RGBWCWWW Discord Chat finishes RGB algorithm.

**Comment by lougovsk** [comment]
@RavenSystem sorry for delay. As promised added the licensing to the added file. Please can you cherry-pick?

**Comment by lougovsk** [comment]
Keeping it alive :)

**Comment by RavenSystem** [comment]
Don't worry. It's alive.

**Pull request closed without merging**
